
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE HAIRSHOP CASCADE CONSTRAINTS;
DROP TABLE DESIGNER CASCADE CONSTRAINTS;
DROP TABLE HAIR_INFO CASCADE CONSTRAINTS;
DROP TABLE DESIGNER_LIST CASCADE CONSTRAINTS;
DROP TABLE LIKES CASCADE CONSTRAINTS;
DROP TABLE STYLE CASCADE CONSTRAINTS;
DROP TABLE STYLE_LIST CASCADE CONSTRAINTS;
DROP TABLE SHOP_PRICE CASCADE CONSTRAINTS;
DROP TABLE RESERVE CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE REVIEW_COMMENT CASCADE CONSTRAINTS;
