-- 테이블 삭제
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE HAIRSHOP CASCADE CONSTRAINTS;
DROP TABLE DESIGNER CASCADE CONSTRAINTS;
DROP TABLE HAIR_INFO CASCADE CONSTRAINTS;
DROP TABLE DESIGNER_LIST CASCADE CONSTRAINTS;
DROP TABLE likes CASCADE CONSTRAINTS;
DROP TABLE STYLE CASCADE CONSTRAINTS;
DROP TABLE STYLE_LIST CASCADE CONSTRAINTS;
DROP TABLE RESERVE CASCADE CONSTRAINTS;

-- 시퀀스 삭제
DROP SEQUENCE hairshop_SEQ;
DROP SEQUENCE designer_SEQ;
DROP SEQUENCE customer_SEQ;
DROP SEQUENCE style_SEQ;
DROP SEQUENCE review_SEQ;
DROP SEQUENCE reserve_SEQ;
DROP SEQUENCE designer_list_SEQ;
DROP SEQUENCE style_list_SEQ;
DROP SEQUENCE likes_SEQ;